spring.config.activate.on-profile=minio

spring.config.import=optional:file:./src/main/resources/connectionBD.properties
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.jdbc=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.springframework.security=DEBUG

# Properties MinIO

# MinIO endpoint (Docker)
app.storage.minio.endpoint=http://localhost:9000
# MinIO permissions
app.storage.minio.access-key=minioadmin
app.storage.minio.secret-key=minioadmin
# Name backet
app.storage.minio.bucket=myapp-photos
# Region (for migration on S3)
app.storage.minio.region=us-east-1
# Created backet on start?
app.storage.minio.create-bucket-on-start=true
# Permission to backet (public/private)
app.storage.minio.bucket-policy=public-read
# time connection
app.storage.minio.connection-timeout=5000
app.storage.minio.read-timeout=10000
# log MinIO
logging.level.io.minio=DEBUG