spring.config.activate.on-profile=local

spring.config.import=optional:file:./src/main/resources/connectionBD.properties
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.jdbc=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.springframework.security=DEBUG

# Created directory for storage photo on start?
app.storage.local.create-on-start=true
# Permissions to file
app.storage.local.file-permissions=755